version: '3.8'

services:
  neo4j:
    image: neo4j:5.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/{NEO4J_PASSWORD}  # Modifique a senha
    ports:
      - "7474:7474"  # Interface do Neo4j
      - "7687:7687"  # Porta do Bolt
    volumes:
      - neo4j_data:/data

  chatbot-python:
    build:
      context: ./chatbot
    container_name: chatbot
    environment:
      - OPENAI_API_KEY={OPENAI_API_KEY}  # Insira sua API Key da OpenAI
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER={NEO4J_USER}
      - NEO4J_PASSWORD={NEO4J_PASSWORD}
    ports:
      - "5000:5000"  # Porta para acessar o ChatBot via API HTTP
    depends_on:
      - neo4j
    volumes:
      - ./chatbot:/app

  chatbot-webapp:
    build:
      context: ./webapp
    container_name: chatbot_webapp
    ports:
      - "8080:8080"  # Porta do WebApp para acessar a interface em estilo ChatGPT
    depends_on:
      - chatbot-python

volumes:
  neo4j_data:
